<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37058" started-at="2018-11-07T21:29:02Z" finished-at="2018-11-07T21:29:39Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.bdd.BDDFundTransfer.RunCukesTestBDD@3c5a99da]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="37058" started-at="2018-11-07T21:29:02Z" finished-at="2018-11-07T21:29:39Z">
      <class name="com.bdd.BDDFundTransfer.RunCukesTestBDD">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.bdd.BDDFundTransfer.RunCukesTestBDD@3c5a99da]" name="setUpClass" is-config="true" duration-ms="463" started-at="2018-11-07T23:29:02Z" finished-at="2018-11-07T23:29:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.bdd.BDDFundTransfer.RunCukesTestBDD@3c5a99da]" name="feature" duration-ms="36363" started-at="2018-11-07T23:29:03Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2018-11-07T23:29:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Customer Transfer's Fund]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: bug beee expected [Transfer failed!! 'John' is not approved. Please contact your branch)] but found [Transfer failed!! 'John' is not approved. Please contact your branch]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: bug beee expected [Transfer failed!! 'John' is not approved. Please contact your branch)] but found [Transfer failed!! 'John' is not approved. Please contact your branch]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: bug beee expected [Transfer failed!! 'John' is not approved. Please contact your branch)] but found [Transfer failed!! 'John' is not approved. Please contact your branch]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.bdd.BDDFundTransfer.FundTransferStepDef.ensure_a_transaction_failure_message_is_displayed(FundTransferStepDef.java:65)
	at ?.Then ensure a transaction failure message "Transfer failed!! 'John' is not approved. Please contact your branch)" is displayed(fundtransfer.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.bdd.BDDFundTransfer.RunCukesTestBDD@3c5a99da]" name="tearDownClass" is-config="true" duration-ms="99" started-at="2018-11-07T23:29:39Z" finished-at="2018-11-07T23:29:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.bdd.BDDFundTransfer.RunCukesTestBDD -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
